In [1]:
import numpy as np
#array creation examples
a=np.array([1,2,3])#1d
a

array([1, 2, 3])

In [3]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
#arrays of zeros,ones,constant
a=np.zeros((3,3))
a=np.ones((3,3))
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [9]:
#range based arrays
a=np.arange(5)
a=np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [10]:
#evenly spaced nos
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
#random arrays
a=np.random.rand(2,3)
a=np.random.randint(0,10,(3,3),dtype="int64")
a

array([[1, 9, 8],
       [3, 5, 8],
       [0, 7, 7]])

In [18]:
#identity matrix/eye
a=np.eye(3)
a=np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#empty array(uninitialized)
a=np.empty((2,3))
a

array([[0.46539748, 0.67850314, 0.17422518],
       [0.00827228, 0.430192  , 0.18177447]])

In [23]:
#bonus reshape
a=np.arange(9)
b=a.reshape(3,3)
b


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
#tile/repeat
a=np.tile([1,2],3)
a=np.repeat([1,2],3)
a

array([1, 1, 1, 2, 2, 2])

In [ ]:
#where to use size parameters
# rand function
import numpy as np
a=np.random.rand(5) #creates a 1d array
a=np.random.rand(2,3) #create a 2d array
#bonus
size=4
a=np.random.rand(size)
a

array([0.36380955, 0.65823155, 0.8861772 , 0.58690378])

In [ ]:
#randint function
a=np.random.randint(0,10,size=6)#1d array with 6 random ints
a=np.random.randint(5,15,size=(3,2))#2d array 3r x 2c
a=np.random.randint(20)
a
# a single no-1d array
# a tuple-shape of the array

12

In [ ]:
#full function
a=np.full(5,7) #here the 1st parameter is size andt the 2nd one is the number
a=np.full((2,3),5) #first paramter is tuple of the shape second one is the number
a

array([7, 7, 7, 7, 7])

In [24]:
#empty function
a=np.empty(4) #1d array with 4 garbage values
a=np.empty((3,3))#2d array with 3x3 array
a




array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
#ones/zeros function
a=np.ones(5) #creates a 1d array of 1s
a=np.zeros((2,3)) #creates a 2d array of 0s
a

array([[0., 0., 0.],
       [0., 0., 0.]])