In [ ]:
import numpy as np

a=np.array([1,2,3])
a

b=np.array([[1,2,3],[4,5,6]])
b[1]

array([4, 5, 6])

In [4]:
c=np.zeros(3)
c

array([0., 0., 0.])

In [7]:
c=np.zeros((3,3,3))
c

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
c=np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
a.itemsize

8

In [10]:
a.nbytes

24

In [33]:
a.dtype

dtype('float64')

In [12]:
a.size*a.itemsize

24

In [17]:
z=np.zeros(10)
z[4]=1
z


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
#create a vector ranging from diff nos
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
#reverse a vector
b=a[::-1]
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [21]:
#create a 3x3 matrix withvalues ranging from 0-8
c=np.arange(0,9).reshape((3,3))
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
#find indices of non 0 element

z=np.nonzero([1,2,3,0,0,8,0,9,0,7,0,])
z


(array([0, 1, 2, 5, 7, 9]),)

In [32]:
#create a 3x3 identity matrix
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
#create a 3x3x3 array with random int values
z=np.random.randint(-1,10,size=(3,3,3))
z

array([[[ 0,  2,  0],
        [ 9,  5,  4],
        [ 2, -1,  5]],

       [[ 1,  7,  8],
        [ 9,  8,  2],
        [-1,  0,  8]],

       [[-1,  7,  3],
        [ 9,  2,  8],
        [ 2,  1,  6]]], dtype=int32)

In [36]:
#create a n array with random values
a=np.random.random((3,3,3))
a

array([[[0.32657567, 0.99238699, 0.89240054],
        [0.98685492, 0.62129573, 0.60851287],
        [0.4679499 , 0.9510135 , 0.22666765]],

       [[0.53188945, 0.9751761 , 0.25825143],
        [0.1967511 , 0.7417045 , 0.35689381],
        [0.54115294, 0.04921181, 0.21974537]],

       [[0.98593452, 0.58615306, 0.59867971],
        [0.258422  , 0.5139754 , 0.64120015],
        [0.48157914, 0.36776992, 0.23115659]]])

In [42]:
#create a 10x10 array with random values and find the minimum and maximum values
a=np.random.randint(0,20,(10,10))
a.max(),a.min()

(np.int32(19), np.int32(0))

In [ ]:
#create a random vector of size 30 and find the mean value
a=np.random.random(30).reshape((10,3))
a.mean()

np.float64(0.47756939173134316)

In [15]:
#create a 2d array with i on the border and 0on the midddle
a=np.array([[1,1,1],[1,1,1],[1,1,1]])
a[1,1]=0
a

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [20]:
shape=7
a=np.ones((shape,shape))
b=np.zeros((shape-2,shape-2))
a.shape,len(a)
a[1:a.shape[0]-1,1:len(a)-1]=b
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [54]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [23]:
arr=np.array([1,2,3])
zero=np.zeros((3,len(arr)+2))
zero[1,1:-1]=arr
zero

array([[0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:

a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [28]:
#how to add a border(filled with 0s)around an existing array
a=np.array([1,2,3,4,5,6])
zero=np.zeros((3,len(a)+2))
zero[1,1:-1]=a
zero

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 4., 5., 6., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [2]:
import numpy as np
a=np.array([1,2,3,4])
a.shape

(4,)

In [ ]:
#outputs
0*np.nan
np.nan==np.nan
np.inf>np.nan
np.nan-np.nan
np.nan in set([np.nan])
0.3==3*0.1

False

In [13]:
#create a 5x5 mtrix ith values 1,2,3,4 just below the diagonal
mat=np.zeros((5,5))
arr=np.arange(1,5)
mat[arr,arr-1]=arr
mat

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])